Repository leighlars/whats-cookin-hb-ll, pull requests merged in 2020-07, with the labels that each got.

#1 Feature/setup read me
  README.md
Labels: documentation

#2 General file set-up
  CSS/style.css
  pull-request-template.md
  src/Ingredients.js
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/domUpdates.js
  src/ingredientsRepository.js
  src/recipesRepository.js
  src/userRepository.js
  test/ingredients-test.js
  test/recipe-test.js
  test/user-test.js
Labels: enhancement

#3 Feature/crude html css
  CSS/style.css
  CSS/styles.css
  assets/calendar.svg
  assets/heart.svg
  assets/logo.svg
  assets/orange.svg
  assets/search.svg
  src/index.html
Labels: enhancement

#4 Add user properties and add import from chai to user-test.js
  src/User.js
  test/user-test.js
Labels: enhancement

#5 Recipe Class/Recipe-test
  src/Recipe.js
  src/User.js
  test/recipe-test.js
  test/user-test.js
Labels: bug, enhancement

#6 Feature/recipe get cost method
  CSS/styles.css
  assets/close.svg
  data/ingredients.js
  data/recipes.js
  src/Recipe.js
  src/index.html
  test/recipe-test.js
Labels: enhancement

#14 Feature/recipe
  src/Recipe.js
  test/recipe-test.js
Labels: enhancement

#15 Feature/user class
  data/ingredients.js
  src/Pantry.js
  src/User.js
  test/user-test.js
Labels: Refactor, enhancement

#18 Add placeholder recipe cards
  CSS/styles.css
  src/index.html
Labels: bug, enhancement

#19 Feature/pantry class
  src/Pantry.js
  test/pantry-test.js
Labels: bug, enhancement

#20 Feature/add card styling
  CSS/styles.css
  assets/closet.svg
  assets/grocerylist.svg
  assets/to-do-list.svg
  src/Pantry.js
  src/index.html
  test/pantry-test.js
Labels: HTML/CSS, bug, enhancement

#21 Pantry Class - findMissingIngredients method and test
  src/Pantry.js
  test/pantry-test.js
Labels: enhancement

#22 Feature/user buttons
  CSS/styles.css
  assets/basket.svg
  src/index.html
Labels: HTML/CSS

#23 Recipes- Add set to search methods, and method to search all queries
  src/Recipe.js
  test/pantry-test.js
  test/recipe-test.js
Labels: enhancement

#24 Feature/user class methods
  src/User.js
  test/user-test.js
Labels: enhancement

#25 Feature/pantry
  src/Pantry.js
  test/pantry-test.js
Labels: enhancement

#26 Feature/add modals to htmlcss
  CSS/styles.css
  assets/heart-active.svg
  assets/list.svg
  src/domUpdates.js
  src/index.html
Labels: HTML/CSS

#27 Linked files in index.html, minor syntax update to domUpdates, added export to user.js
  data/users.js
  src/Pantry.js
  src/domUpdates.js
  src/index.html
  src/scripts.js
  test/pantry-test.js
  test/user-test.js
Labels: bug

#28 Feature/sadPathsandRefactoring
  src/Ingredients.js
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/domUpdates.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: bug, enhancement

#32 Feature/pantry fix
  src/Pantry.js
  test/pantry-test.js
Labels: enhancement

#33 Clean up pantry class file notes
  src/Pantry.js
  test/pantry-test.js
Labels: Refactor

#34 Modified Recipe class and test to use mock data
  src/Ingredients.js
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/domUpdates.js
  src/index.html
  src/ingredientsRepository.js
  src/recipesRepository.js
  src/scripts.js
  src/userRepository.js
  test/ingredients-test.js
  test/recipe-test.js
  test/user-test.js
Labels: enhancement

#35 Feature/Refactor and clean up class and test files
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: Refactor, enhancement

#37 Feature/dom updates
  CSS/styles.css
  src/User.js
  src/domUpdates.js
  src/index.html
  src/scripts.js
Labels: enhancement

#38 Feature/class data refactor
  src/Pantry.js
  src/Recipe.js
  src/User.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: enhancement

#42 Feature/recipe modal
  src/scripts.js
Labels: bug, enhancement

#43 Feature/modal
  CSS/styles.css
  src/index.html
  src/scripts.js
Labels: bug, enhancement

#44 Feature/recipe modal
  src/index.html
  src/scripts.js
Labels: bug, enhancement

#45 Add instructions and cost to modal, broke tags in Recipe class
  src/Recipe.js
  src/scripts.js
  test/recipe-test.js
Labels: bug, enhancement

#46 Feature/recipe modal
  CSS/styles.css
  src/index.html
  src/scripts.js
Labels: enhancement

#47 Feature/recipe modal
  src/Recipe.js
  src/User.js
  src/scripts.js
  test/recipe-test.js
Labels: bug, enhancement

#48 Feature/recipe modal
  src/scripts.js
Labels: enhancement

#49 Feature/display recipes
  CSS/styles.css
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
  test/pantry-test.js
  test/recipe-test.js
Labels: bug, enhancement

#51 Unable to figure out logic to display pantry content in modal
  src/Pantry.js
  src/User.js
  src/scripts.js
  test/pantry-test.js
Labels: bug

#53 Feature/pantry modal
  CSS/styles.css
  src/Pantry.js
  src/Recipe.js
  src/index.html
  src/scripts.js
  test/pantry-test.js
Labels: enhancement

#56 Add displaySearchedSaved function, not presently working
  src/User.js
  src/scripts.js
Labels: bug, enhancement

#57 Feature/filter tags
  CSS/styles.css
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: bug, enhancement

#58 Feature/search saved planned
  CSS/styles.css
  src/User.js
  src/index.html
  src/scripts.js
Labels: enhancement

#59 Feature/search
  CSS/styles.css
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
  test/user-test.js
Labels: HTML/CSS, bug, enhancement

#62 Fix last 3 test of User.js and clean up all primary files
  CSS/styles.css
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/index.html
  src/scripts.js
  test/pantry-test.js
  test/recipe-test.js
  test/user-test.js
Labels: enhancement
